const theme = {
  primary: '#ff8c00',
  'primary-lighten': '#ffa332',
  'primary-darken': '#ffa332',
  red: '#f44336',
  orange: '#f77519',
  'red-lighten': '#f66',
  yellow: '#ff0',
  white: '#fff',
  'border-darker': '#c0c4cc',
  'border-primary': '#c6c6c8',
  'tooltip-bg': ' hsla(0,0%,6%,.97)',
  'tooltip-color': '#fff',
  'placeholder-block-bg': '#eee',
  'range-thumb': '#fff',
  'range-thumb-border': 'rgba(0, 0, 0, 0.04)',
  'range-thumb-shadow': 'rgba(0, 0, 0, 0.15)',
};
